### PR TITLE
Add PowerShell Syntax Highlighting

### PR DESCRIPTION
**Pull request by michaeltlombardi**
Modified the PowerShell syntax highlighting from [m0t0k1](https://github.com/m0t0k1/kate-powershell)'s repository to include PowerShell v5 commands.

### CODE REVIEW

**Comment by KyleOndy** [comment]
I'm love to have powerhouse syntax highlighting included. Is there an issue blocking this merge?

**Comment by jgm** [comment]
- Adding the xml file alone is not sufficient (see README)
- Is this xml file in upstream (official kate repository)?  If not, can you submit it there?
- The filename doesn't seem to follow the conventions used in kate (lowercase powershell.xml would be more consonant with what is there)

**Comment by KyleOndy** [comment]
My apologies for not reading the documentation.

I'll see if I can find the upstream source and submit a fixed file there.

**Comment by michaeltlombardi** [comment]
> You may modify the xml files in this directory, or add new ones, and then regenerate the parsers by doing:
> 
> `make prep`
>
> ...

@jgm, sorry for the failure to follow directions, somehow I missed the relevant above. I'll see about pulling down the project and submitting this the **correct** way and with updated casing.

I'll submit the correct commits to the official kate repository as well.

**Pull request closed without merging**
