### PR TITLE
Fixing incorrectly capitalized regexps.

### PR DESCRIPTION
**Pull request by blackgnezdo**
Originally found and fixed by Sam Allen.

### CODE REVIEW

**Comment by jgm** [comment]
These should be fixed upstream (we get them from KDE's
syntax highlighting engine).

Also, highlighting-kate has been superseded by skylighting,
which is used in current versions of pandoc.

**Comment by blackgnezdo** [comment]
Do you have a reference to their repo? I couldn't quickly identify a place to send a patch.

**Comment by jgm** [comment]
See the README for jgm/skylighting.

+++ Greg Steuck [Sep 11 17 21:55 ]:

**Comment by blackgnezdo** [comment]
Now at https://phabricator.kde.org/D7792

**Pull request closed without merging**
